### ISSUE TITLE
Ozette on Master won't build on OS X 10.11

### ISSUE THREAD

**Issue by lewisde** [marssaxman/ozette#33]
➜  ozette-master  sudo make
compiling ozette
checking dependencies...
compiling src/dialog/input.cpp...
src/dialog/input.cpp:80:24: error: no member named 'abs' in namespace 'std'
                        int selcount = std::abs((int)_cursor_pos - (int)...
                                       ~~~~~^
1 error generated.
make: **\* [executable] Error 1
➜  ozette-master  make clean
➜  ozette-master  sudo make install
cp: ozette: No such file or directory
make: **\* [install] Error 1
➜  ozette-master  sudo make
compiling ozette
checking dependencies...
compiling src/app/config.cpp...
compiling src/app/ozette.cpp...
In file included from src/app/ozette.cpp:20:
In file included from ./src/app/ozette.h:25:
./src/browser/browser.h:40:19: warning: 'priority' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Primary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
In file included from src/app/ozette.cpp:20:
./src/app/ozette.h:39:15: warning: 'find_in_file' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual void find_in_file(std::string path, Editor::line_t index);
                     ^
./src/app/controller.h:37:15: note: overridden virtual function is here
        virtual void find_in_file(std::string path, size_t index) = 0;
                     ^
In file included from src/app/ozette.cpp:24:
./src/console/console.h:43:19: warning: 'priority' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Secondary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
In file included from src/app/ozette.cpp:25:
./src/search/search.h:40:19: warning: 'priority' overrides a member function but
      is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Secondary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
4 warnings generated.
compiling src/app/path.cpp...
compiling src/app/syntax.cpp...
compiling src/browser/browser.cpp...
In file included from src/browser/browser.cpp:20:
./src/browser/browser.h:40:19: warning: 'priority' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Primary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
1 warning generated.
compiling src/browser/dirtree.cpp...
compiling src/console/console.cpp...
In file included from src/console/console.cpp:20:
./src/console/console.h:43:19: warning: 'priority' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Secondary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
1 warning generated.
compiling src/console/log.cpp...
compiling src/console/popenRWE.cpp...
compiling src/console/subproc.cpp...
compiling src/dialog/confirmation.cpp...
compiling src/dialog/form.cpp...
compiling src/dialog/input.cpp...
src/dialog/input.cpp:80:24: error: no member named 'abs' in namespace 'std'
                        int selcount = std::abs((int)_cursor_pos - (int)...
                                       ~~~~~^
1 error generated.
compiling src/editor/changelist.cpp...
compiling src/editor/coordinates.cpp...
compiling src/editor/cursor.cpp...
compiling src/editor/displayline.cpp...
compiling src/editor/document.cpp...
compiling src/editor/editor.cpp...
compiling src/editor/settings.cpp...
compiling src/editor/update.cpp...
compiling src/inih/ini.c...
compiling src/inih/INIReader.cpp...
compiling src/main.cpp...
In file included from src/main.cpp:20:
In file included from ./src/app/ozette.h:25:
./src/browser/browser.h:40:19: warning: 'priority' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Primary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
In file included from src/main.cpp:20:
./src/app/ozette.h:39:15: warning: 'find_in_file' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
        virtual void find_in_file(std::string path, Editor::line_t index);
                     ^
./src/app/controller.h:37:15: note: overridden virtual function is here
        virtual void find_in_file(std::string path, size_t index) = 0;
                     ^
2 warnings generated.
compiling src/search/dialog.cpp...
compiling src/search/search.cpp...
In file included from src/search/search.cpp:20:
./src/search/search.h:40:19: warning: 'priority' overrides a member function but
      is not marked 'override' [-Winconsistent-missing-override]
        virtual Priority priority() const { return Priority::Secondary; }
                         ^
./src/ui/view.h:54:19: note: overridden virtual function is here
        virtual Priority priority() const { return Priority::Any; }
                         ^
1 warning generated.
compiling src/ui/colors.cpp...
compiling src/ui/helpbar.cpp...
compiling src/ui/shell.cpp...
compiling src/ui/view.cpp...
compiling src/ui/window.cpp...
make: **\* [executable] Error 1
➜  ozette-master
